### ISSUE TITLE
Can not select from list: loses focus

### ISSUE THREAD

**Issue by MarcelOnck** [sebdah/meteor-autocompletion#12]
I have two apps using the autocompletion package. App "B" is an exact copy of app "A". In app "A" the autocompletion list allows for selection of an entry in the list by mouse or cursor-keys, but app "B" does not: as soon as I move the mouse to select an entry in the list shown, the list disappears.....
It makes no difference if I use the mouse or the cursors keys: if I want to go into the list, the list disappears. In app "A", this works all as it should. I have no idea what to look for.
I just removed and reinstalled the autocompletion package to make sure I use the latest one, but it makes no difference.
Using "meteor list" gives no information since it states version number 0.0.0. in both app "A" and "B".
The smart.lock file shows "v.0.1.4" under tag.

What could cause this?

**Comment by sebdah** [comment]
Sorry, but it's very difficult to know what it might be. I'd suggest that you start looking the console and see if there are any errors. Otherwise try to add some debug output to your code to see where it issue occurs. Another option would be to try to isolate the dropdown from as many potentially disturbing items as possible (i.e. overlapping CSS or conflicting namespaces).

**Comment by MarcelOnck** [comment]
Hi Sebastian,

Thanks for your suggestions! I understand it is almost impossible to
troubleshoot from a distance. However, you might have heard about it before.
I tried the error log option, but no errors where reported, every data was
presented just fine.
The problem does not seem to be in the lookup that is populating the list.
The list looks just fine. The problem is that when I try to hover my mouse
above it, it will just lose focus and vanish on me so I can't click it. It
is visible, but there seems to be something that prevents me from being
able to actually select something from within the list.
No visible errors in the console nor in the log that appears in the console.

Strange, not?

Best regards,
Marcel

**Comment by sebdah** [comment]
It's strage. I'd suggest that has to do with jQueryUI. Maybe you have another version of jQuery installed in one of the installations? This package fetches jQuery UI 1.9.2.

**Comment by MarcelOnck** [comment]
A "meteor list" command on both application servers shows, that server A has installed:
jquery 1.0.0. Manipulate the DOM using CSS Selectors
jQuery UI 1.9.2. is NOT reported in this list.
Server A's application works CORRECTLY.

Looking at server B, it has installed:
jquery 1.0.0. Manipulate the DOM using CSS Selectors (so looks the same as server A)
jQuery UI 1.9.2. is NOT reported in this list.
Server B's application works NOT correctly.

When I look at the buildinfo.json file in the meteorite meteor-autocompletion .build directory, it lists among other stuff on server A:
"autocompletion": "/home/action/workspace/jouwwebkantoor/packages/autocompletion",
    "meteor": "/home/action/.meteor/packages/meteor/d06ae22393",
    "jquery-ui": "/home/action/workspace/jouwwebkantoor/packages/jquery-ui"

Server B doesn't even HAVE such a file, nor any .build directory at all. It does have a versions.json file however, which states among other stuff:  "dependencies": [
    [
      "jquery",
      "1.0.0"
    ],
    [
      "jquery-ui",
      "0.0.0"
    ],

So it lists 2 jquery packages there as dependencies. It seems the installs of autocompletion on server A varies from the install on server B. Different directories, different files in them.

What to do?
