### ISSUE TITLE
Why does this not work for publish/subscribe model?

### ISSUE THREAD

**Issue by kaushik1979** [sebdah/meteor-autocompletion#8]
I thought the primary purpose of publish-subscribe was to safe-guard the data from malicious attacks. Is this plugin not going against that?

My requirement is that i want to add a functionality to send an email to some users as well as some groups (made up of users). How can I bind the search to a publish function on server?

**Comment by sebdah** [comment]
I don't think I follow what you mean, can you please elaborate a bit more on this?

This package is utilising the published data, right?

**Comment by kaushik1979** [comment]
My bad.
