### ISSUE TITLE
mrt add meteor-autocompletion does not work

### ISSUE THREAD

**Issue by kaushik1979** [sebdah/meteor-autocompletion#9]
mrt add meteor-autocompletion

/usr/local/lib/node_modules/meteorite/lib/project.js:225
          throw("Package named " + pkgName + " doesn't exist in your meteor in
                                           ^
Package named meteor-autocompletion doesn't exist in your meteor installation, smart.json, or on atmosphere

**Comment by sebdah** [comment]
This is a bug in the docs.. The proper command should be:

```
mrt add autocompletion
```
